[tox]
envlist = 3.10, 3.11, 3.12, 3.13, 3.13t, 3.14, 3.14t

[testenv]
deps = 
    ruff
    mypy
    pytest
    uvloop ; sys_platform != 'win32'
    winloop ; sys_platform == 'win32'
commands = 
    ruff format
    ruff check
    mypy .
    pytest
